version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: money-flow
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"